### ISSUE TITLE
Chain never synch

### ISSUE THREAD

**Issue by alfhv** [stratisproject/FederatedSidechains#74] opened 2018-08-21 22:39 UTC
I was following all steps to setup sidechain wallet but when starting stratis.SidechainD (on testnet) the chain is never synchronized, all headers remain zero always:

info: Stratis.Bitcoin.FullNode[0]
      ======Node stats====== 08/21/2018 22:33:58 agent StratisBitcoin:1.1.13
      Headers.Height:      0        Headers.Hash:     0000e451752bac9f67cb5d63fd32442ba42d42b1b2ea28131d91e1e3f29f523b
      BlockStore.Height:   0        BlockStore.Hash:  0000e451752bac9f67cb5d63fd32442ba42d42b1b2ea28131d91e1e3f29f523b
      Consensus.Height:    0        Consensus.Hash:   0000e451752bac9f67cb5d63fd32442ba42d42b1b2ea28131d91e1e3f29f523b
      Wallet.Height:       0        Wallet.Hash:      0000e451752bac9f67cb5d63fd32442ba42d42b1b2ea28131d91e1e3f29f523b

      ======Mempool======
      MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0

All TSTRAT sent to sidechain address are confirmed in mainchain side but never received in sidechain.

please advice, thanks

**Comment by bokobza** [comment] 2018-10-10 14:55
ah this is because the sidechain we created for the alpha was there as an example only and was taken down.
The best way for you to make this work would be to create your own sidechain 😉 
Closing this as not a bug.

**Closed by bokobza** 2018-10-10 14:55 UTC
Labels: bug
